---
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /

vocabulary_core:
    resource: "@VocabularyCoreBundle/Resources/config/routing.yml"
    prefix:   /api

vocabulary_user:
    resource: "@VocabularyUserBundle/Resources/config/routing.yml"
    prefix:   /api/user/

vocabulary_quiz:
    resource: "@VocabularyQuizBundle/Resources/config/routing.yml"
    prefix:   /api
